import { Link } from "react-router";

import { useAuth } from "../auth/RequireAuth";

export function LandingPage() {
  const { session } = useAuth();

  return <section className="landing" aria-labelledby="landing-title"><div className="landing__copy"><p className="eyebrow">Resume Intelligence Portal</p><h1 id="landing-title">A clearer way to review resumes.</h1><p className="landing__lede">Candidates submit a PDF for a role. Recruiters review the role’s compatibility results once processing is complete.</p><div className="landing__actions">{session ? <Link className="button button--primary" to="/session">View your session</Link> : <><Link className="button button--primary" to="/signup">Create account</Link><Link className="button button--secondary" to="/login">Sign in</Link></>}</div></div><div className="workflow-panel"><p className="eyebrow">The workflow</p><svg className="workflow-visual" viewBox="0 0 560 250" aria-hidden="true"><rect x="26" y="32" width="130" height="168" rx="8" fill="#FFFCF6" stroke="#8A796A" strokeWidth="2"/><path d="M58 74h66M58 99h66M58 124h43" fill="none" stroke="#593D2B" strokeWidth="7" strokeLinecap="round"/><path d="M156 116h80M326 116h80" fill="none" stroke="#593D2B" strokeWidth="3" strokeDasharray="7 8"/><path d="m221 102 18 14-18 14" fill="none" stroke="#593D2B" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/><path d="m391 102 18 14-18 14" fill="none" stroke="#593D2B" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/><rect x="236" y="68" width="90" height="34" rx="17" fill="#FFFCF6" stroke="#8A796A" strokeWidth="2"/><rect x="236" y="130" width="90" height="34" rx="17" fill="#FFFCF6" stroke="#8A796A" strokeWidth="2"/><text x="281" y="90" textAnchor="middle" fill="#211B17" fontFamily="system-ui, sans-serif" fontSize="15">Skills</text><text x="281" y="152" textAnchor="middle" fill="#211B17" fontFamily="system-ui, sans-serif" fontSize="15">Role</text><rect x="408" y="50" width="126" height="132" rx="8" fill="#593D2B"/><path d="M436 93h70M436 118h55M436 143h38" fill="none" stroke="#FFFCF6" strokeWidth="7" strokeLinecap="round"/></svg><p className="workflow-caption">Resume <span aria-hidden="true">→</span> role skills <span aria-hidden="true">→</span> ranked shortlist</p></div></section>;
}
